title: "Shubham S. Ghodake"
description: "2nd Year PhD Student at IISc Bangalore | Tensor Analysis · Machine Learning · Optimization"
theme: minima
url: "https://Zeus9637353238.github.io"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
navbar-links:
  Home: "index"
  About: "about"
  Research: "research"
  Publications: "publications"
  Teaching: "teaching"
  CV: "cv"
  Contact: "contact"

# Social
github_username: Zeus9637353238
linkedin_username: shubham-ghodake-2b7a221b1
email: sgshubham@iisc.ac.in
