title: Shubham Ghodake
description:  PhD Scholar,IISc Banglore
theme: jekyll-theme-cayman

# Social links (optional)
github_username: Zeus9637353238
linkedin_username: https://www.linkedin.com/in/shubham-ghodake-2b7a221b1
email: sgshubham@iisc.ac.in

# Build settings
markdown: kramdown
